version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: vo-api:latest
    container_name: vo-api
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/virtual_ai_org
      JWT_SECRET: change-me
      ALLOW_SIGNUP: "true"
      USE_REDIS_STREAM: "true"
      REDIS_URL: redis://redis:6379/0
      STORE_TO_S3: "true"
      S3_BUCKET: vo-artifacts
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      AWS_REGION: us-east-1
      S3_ENDPOINT_URL: http://minio:9000
      LINEAR_MOCK: "true"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
      minio-mc:
        condition: service_completed_successfully
    volumes:
      - ./data:/app/data

  console:
    build:
      context: .
      dockerfile: Dockerfile.console
      args:
        VITE_API_BASE: http://localhost:8000
    image: vo-console:latest
    container_name: vo-console
    ports:
      - "5173:5173"
    depends_on:
      api:
        condition: service_started

  postgres:
    image: postgres:15-alpine
    container_name: vo-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: virtual_ai_org
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: vo-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: vo-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

  minio-mc:
    image: minio/mc:latest
    container_name: vo-minio-mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 minio minio123 &&
      mc mb -p local/vo-artifacts || true &&
      mc anonymous set download local/vo-artifacts || true &&
      exit 0
      "

volumes:
  pgdata:
  minio:
