# Fly.io config for the Console
app = "vo-console-REPLACEME"  # change to your unique app name

primary_region = "iad"

[build]
  dockerfile = "Dockerfile.console"

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
