name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Install deps
        run: uv sync --all-extras
      - name: Lint
        run: uv run ruff check .
      - name: Tests
        run: uv run pytest -q
      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.api
          push: false
          load: true
          tags: vo-api:ci
      - name: Build console image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.console
          push: false
          load: true
          tags: vo-console:ci
